// Date validation helpers

/**
 * Validates a plain date in YYYY-MM-DD format.
 * Enforces calendar correctness (e.g. rejects leap year errors, invalid month numbers, February 30).
 */
export function isValidPlainDate(value: any): boolean {
  if (typeof value !== "string") return false;
  
  // Format check
  const regex = /^\d{4}-\d{2}-\d{2}$/;
  if (!regex.test(value)) return false;

  const parts = value.split("-");
  const year = parseInt(parts[0], 10);
  const month = parseInt(parts[1], 10);
  const day = parseInt(parts[2], 10);

  if (month < 1 || month > 12) return false;
  if (day < 1 || day > 31) return false;

  // Calendar validity check (relying on JS Date wrapping verification)
  const dateObj = new Date(year, month - 1, day);
  if (
    dateObj.getFullYear() !== year ||
    dateObj.getMonth() !== month - 1 ||
    dateObj.getDate() !== day
  ) {
    return false;
  }

  return true;
}

/**
 * Validates a budget month in YYYY-MM format.
 * Enforces month is between 01 and 12.
 */
export function isValidBudgetMonth(value: any): boolean {
  if (typeof value !== "string") return false;

  const regex = /^\d{4}-\d{2}$/;
  if (!regex.test(value)) return false;

  const parts = value.split("-");
  const month = parseInt(parts[1], 10);

  if (month < 1 || month > 12) return false;

  return true;
}

/**
 * Validates a full ISO 8601 timestamp (e.g., generated by new Date().toISOString()).
 */
export function isValidTimestamp(value: any): boolean {
  if (typeof value !== "string") return false;

  // Regex matches standard ISO timestamps, e.g. YYYY-MM-DDTHH:mm:ss.sssZ or with timezone offset
  const regex = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})$/;
  if (!regex.test(value)) return false;

  // Check if it is a parsable date
  const timestamp = Date.parse(value);
  if (isNaN(timestamp)) return false;

  return true;
}
